# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: maparmar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/28 01:27:24 by maparmar          #+#    #+#              #
#    Updated: 2019/03/28 01:34:08 by maparmar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:= fillit

#directories
LIB_FT	:=	libft
OBJ_DIR :=	./obj

SRC		:=  free_function.c \
			helper.c \
			main.c \
			maker.c \
			parser.c \
			solve_map.c

OBJ		:=	$(addprefix $(OJ_DIR)/,$(SRC: .c= .o))


